@startuml
actor Student
participant Monitor
participant Authentication
participant Reservation
participant AVRoom

Student -> Monitor: open Login page
activate Monitor
Monitor -> Authentication: login(username, password)
activate Authentication
Authentication -> Monitor: login success
deactivate Authentication
Monitor -> Student: display library page

Student -> Monitor: select AV room reservation option
Monitor -> AVRoom: getRoomList()
activate AVRoom
AVRoom -> Monitor: room details
deactivate AVRoom
Monitor -> Student: display room details

Student -> Monitor: click reserve room
Monitor -> Reservation: reserveRoom(roomID)
activate Reservation
Reservation -> AVRoom: createReservation(studentID, roomID, reservationType)
activate AVRoom
deactivate AVRoom
Reservation -> Monitor: reservation created
deactivate Reservation
Monitor -> Student: display reservation confirmation
@enduml
