@startuml
actor Student
participant Monitor
participant Authentication
participant Reservation
participant RoomManagement
participant AVRoom

Student -> Monitor: open Login page
activate Monitor
Monitor -> Authentication: login(username, password)
activate Authentication
Authentication -> Monitor: login success
deactivate Authentication
Monitor -> Student: display library page

Student -> Monitor: select AV room reservation option
Monitor -> RoomManagement: getRoomList()
activate RoomManagement
RoomManagement -> AVRoom: getRoomData()
activate AVRoom
AVRoom -> RoomManagement: room data
deactivate AVRoom
RoomManagement -> Monitor: list of room
deactivate RoomManagement
Monitor -> Student: display rooms

Student -> Monitor: click reserve room
Monitor -> Reservation: reserveRoom(roomID)
activate Reservation
Reservation -> RoomManagement: createReservation(studentID, roomID, reservationType)
activate RoomManagement
RoomManagement -> AVRoom: updateRoom(room: Room)
activate AVRoom
deactivate AVRoom
RoomManagement -> Reservation: confirm update
deactivate RoomManagement
Reservation -> Monitor: reservation created
deactivate Reservation
Monitor -> Student: display reservation confirmation
@enduml
