@startuml
left to right direction

class Authentication {
    -username: String
    -password: String
    -email: String
    +register(username: String, password: String, email: String): void
    +login(username: String, password: String): void
    +logout(): void
}

class User {
    -userID: String
    -username: String
    -email: String
    -password: String
    -loanID: String[]
    +searchBook(bookDetails: String): Book[]
    +getRoomList(): AVRoom[]
    +borrowBooks(bookID: String[]): void
    +returnBooks(loanID: String): void
    +renewReturnDate(loanID: String): void
}

class Student {
    -studentID: String
    +reserveBook(bookID: String[]): void
    +reserveRoom(roomID: String[]): void
}

class Book {
    -bookID: String
    -title: String
    -author: String
    -genre: String
    -loanStatus: Boolean
    -reserveStatus: Boolean
}

class Loan {
    -loanID: String
    -userID: String
    -bookID: String[]
    -borrowDate: Date
    -dueDate: Date
    -returnDate: Date
    +createLoan(userID: String, bookID: String[]): void
    +renewLoan(): void
    +closeLoan(): void
}

class Administrator {
    -adminID: String
    +displayRegisteredUsers(): void
    +displayUsersWithBorrowedBooks(): void
}

class Reservation {
    -reservationID: String
    -studentID: String
    -itemID: String[]
    -reservationDate: Date
    -reservationType: String
    +createReservation(studentID: String, itemID: String[], reservationType: String): void
}

class AVRoom {
    -roomID: String
    -studentID: String
    -reserveStatus: Boolean
}

User -up-> Authentication: uses
User ---> Book: queries
User --> AVRoom: queries
User <|-right- Student
User "1" -- "\n0..*" Loan: creates
Student "1" -- "0..*" Reservation: creates
AVRoom "1" -right- "0..*" Reservation: "                              is reserved in"
Book "1...5" -up- "\n0..*" Loan: is borrowed in
Book "\n1...5" -up- "0..*" Reservation: is reserved in
Administrator -right-> User: "                   queries"
Administrator -up-> Authentication: uses
Administrator --> Loan : queries
@enduml
