@startuml
actor Administrator
participant Monitor
participant Authentication
participant Loan
participant UserManagement
participant User


Administrator -> Monitor: open Login page
activate Monitor
Monitor -> Authentication: login(username, password)
activate Authentication
Authentication -> Monitor: login success
deactivate Authentication
Monitor -> Administrator: display library page



alt All Registration User
    Administrator -> Monitor: select display registered users
    Monitor -> UserManagement: displayRegisteredUsers()
    activate UserManagement

    UserManagement -> User: getUserData(user: User[])
    activate User
    User -> UserManagement: user data
    deactivate User
    UserManagement -> Monitor: list of registered users
    deactivate UserManagement
    Monitor -> Administrator: display list of registered users
else With Borrowed Books
    Administrator -> Monitor: select display users with borrowed books
    Monitor -> Loan: displayUsersWithBorrowedBooks()
    activate Loan
    Loan -> UserManagement: send userID
    deactivate Loan
    activate UserManagement

    UserManagement -> User: getUserData(user: User[])
    activate User
    User -> UserManagement: user data
    deactivate User
    UserManagement -> Monitor: return user details
    deactivate UserManagement

    Monitor -> Administrator: display users with borrowed books
end
@enduml
