@startuml
actor All_User
participant Monitor
participant Authentication
participant UserManagement
participant User



All_User -> Monitor: open registration form
activate Monitor
Monitor -> All_User: display registration form

All_User -> Monitor: type registration details (username, password, email)
Monitor -> Authentication: submit user data (username, password, email)
activate Authentication
Authentication -> UserManagement: register(username, password, email)
activate UserManagement
UserManagement -> User: addUser(user: User)
activate User
User -> UserManagement: new user
deactivate User
UserManagement -> UserManagement: update own user[]
UserManagement -> Authentication: send created confirmation
deactivate UserManagement
Authentication -> Monitor: registration success
deactivate Authentication
Monitor -> All_User: display success message

@enduml
