@startuml
actor User
participant Monitor
participant Authentication
participant Loan
participant BookManagement
participant Book

User -> Monitor: open Login page
activate Monitor
Monitor -> Authentication: login(username, password)
activate Authentication
Authentication -> Monitor: login success
deactivate Authentication
Monitor -> User: display library page

User -> Monitor: select return book option
Monitor -> Loan: getLoanList()
activate Loan
Loan -> Monitor: list of user's loan
deactivate Loan
Monitor -> User: display user's loan lists

User -> Monitor: select loan to return
Monitor -> Loan: returnBooks(loanID)
activate Loan
Loan -> BookManagement: closeLoan()
activate BookManagement
BookManagement -> Book: updateBook(book: Book)
activate Book
deactivate Book
BookManagement -> Loan: confirm update
deactivate BookManagement
Loan -> Monitor: return confirmation
deactivate Loan
Monitor -> User: display return confirmation
@enduml
