@startuml
actor User
participant Monitor
participant Authentication
participant Loan
participant Book

User -> Monitor: open
Monitor -> Authentication: login(username, password)
Authentication -> Monitor: login success
Monitor -> User: display library page

User -> Monitor: select return book option
Monitor -> Loan: getLoanList()
Loan -> Monitor: list of user's loan
Monitor -> User: display user's loan lists

User -> Monitor: select loan to return
Monitor -> Loan: returnBooks(loanID)
Loan -> Book: closeLoan()
Loan -> Monitor: return confirmation
Monitor -> User: display return confirmation
@enduml
